### ISSUE TITLE
需要修很多bug才能跑通

### ISSUE THREAD

**Issue by fbicirno** [yuyuko-C/War3GameFramework#1]
比如有一处icon 写成了ico
调用game.Frame但是全局变量game不存在
为什么会这样

**Comment by yuyuko-C** [comment]
感谢反馈, 之前未发现这些问题, 重新执行后的确发现了许多小问题. 现已修复. 可重新拉取
game的全局变量不存在这个问题我尚未发现, 此变量定义在[map/lua/base.lua]文件中, 这是整个工程最开始的地方,按理说不会出现不存在的情况. 
如需要帮助解决请提供更加详细的信息.

**Comment by fbicirno** [comment]
请问这个工程可以和内置japi结合用作项目的底层吗

**Comment by fbicirno** [comment]
入口处，应该像内置一样用xpcall返回require的报错堆栈，以防止代码中断无法查错

**Comment by yuyuko-C** [comment]
> 请问这个工程可以和内置japi结合用作项目的底层吗

可以使用内置JAPI,此项目多次使用了JAPI来实现功能.

**Comment by yuyuko-C** [comment]
> 入口处，应该像内置一样用xpcall返回require的报错堆栈，以防止代码中断无法查错

能否指出修改的具体文件和行数以及修改前后的对比

**Comment by fbicirno** [comment]
require main那个地方
xpcall(function ()
    require 'main'
end, function (msg)
    print(msg, '\n', debug.traceback())
end)

**Comment by yuyuko-C** [comment]
已处理, 感谢!
