### ISSUE TITLE
不能生成RSA

### ISSUE THREAD

**Issue by junshangshui** [yuyuko-C/War3GameFramework#2]
![wwwwwwwwwwwwwwwww](https://github.com/yuyuko-C/War3GameFramework/assets/40519621/b76e3a9d-dc61-45c2-80f7-9ccd7768d652)

我的系统是Win11，也有.net core 3.1 .net6 7，以管理员运行cmd也这样,请问这是怎么回事

**Comment by yuyuko-C** [comment]
看起来你是运行后直接按了回车, 你需要在运行启动后输入3再按回车.
